name: Manifests Validation
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  lint-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
      - name: Validate Kustomize Manifests
        run: |
          ./scripts/validate_manifests.sh

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
      - name: Validate Manifests using yamllint
        uses: frenck/action-yamllint@v1

  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
      - name: Validate Helm charts
        run: |
          ./scripts/validate_charts.sh

  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.52.0
        with:
          config_path: .spellcheck.yaml
